// @vardi/checklists — Package-owned runtime seam for seeded checklist, legal,
// and risk-matrix catalog data. Seed asset files remain internal details.
export type {
  CanonicalLegalReference,
  LegalReference,
  LegalReferenceCatalog,
  RiskLevel,
  RiskMatrix,
  SeedChecklist,
  SeedChecklistMetadata,
  SeedChecklistSummary,
  SeedCriterion,
  SeedCriterionTranslations,
  SeedManifest,
  SeedSection,
  SeedTitleTranslations,
  SeedTranslation,
  UnresolvedImportedLegalReference,
} from "./runtime.js";
export {
  getLegalReferenceByCode,
  getLegalReferenceCatalog,
  getRiskMatrixById,
  getRiskMatrixBySlug,
  getSeedChecklistById,
  getSeedChecklistBySlug,
  getSeedManifest,
  listLegalReferences,
  listRiskMatrices,
  listSeedChecklists,
} from "./runtime.js";
